apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    component: server
spec:
  containers:
    - name: server-container
      image: server-image
      imagePullPolicy: Never
      ports:
        - containerPort: 8000