apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip
  namespace: k8s-tut
  labels:
    component: postgres-cluster-ip
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
   component: postgres-deployment