apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: k8s-tut
spec:
  selector:
    matchLabels:
      component: client-deployment
  template:
    metadata:
      labels:
        component: client-deployment
    spec:
      containers:
      - name: client
        image: k8s-client
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500Mi"
            cpu: "1"
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: cluster-env
                key: redis_url
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: cluster-env
                key: db_user
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: cluster-env
                key: db_host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: cluster-env
                key: db_name
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: cluster-env
                key: db_port
          # This is a secret reference, which typically gets imperatively created
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpassword
                key: DB_PASSWORD
