version: '3'
services:
  redis-server:
    image: redis
  app:
    build: .
    ports:
      - "8000:8000"
  app-2:
    build: .
    ports:
      - "8001:8000"
  app-3:
    build: .
    ports:
      - "8002:8000"