import { Metadata } from "next"
import "./(styles)/global.css"
import AuthContextProvider from "./auth/_context/provider"
import initialiseEnv from "./config";
import ToastContextProvider from "./(components)/toast/context";
initialiseEnv();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" id="app">
      <body className="bg-slate-800 text-white px-[3rem]">
        <AuthContextProvider>
          <ToastContextProvider>
            {children}
          </ToastContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
