apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: k8s-tut
spec:
  # NOTE: Only one pod for local setup, this is not good for prod setup!
  replicas: 1
  selector:
    matchLabels:
      component: redis-deployment
  template:
    metadata:
      labels:
        component: redis-deployment
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        # For container startup, run 'redis-server'
        command:
          - redis-server
        # Normal workload will provision 16MB memory and 63 millicpu time, limits are doubled
        resources:
          requests:
            memory: "16Mi"
            cpu: "63m"
          limits:
            memory: "32Mi"
            cpu: "125m"
        ports:
        - containerPort: 6379
        # These defines paths withinm container environment that maps to volumes on Pod
        volumeMounts:
          - mountPath: /redis-data
            name: data
          - mountPath: /redis
            name: config
      # These volumes exists on the Pod
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          emptyDir: {}

